### ISSUE TITLE
Transactions in the account API

### ISSUE THREAD

**Issue by scottcowan** [SkillsFundingAgency/das-employerapprenticeshipsservice#739]
I would like to access financial transactions from the account API for the support console to show what support people need to have to handle a support call. They should see what employers see.

including
# payments in
## levy credit
- we would like a breakdown by PAYE scheme
- the levy credit - _all submission for a payroll period_
- the english fraction
- the 10% top up(?) 
- combined total
## payments and refunds - this isn't confirmed from the payments yet
- who it comes from
- what it's for
- the amount
- uln
- name
- ukprn
- provider name
- date collection period
- how the payment is split in terms of levy debit, co-investment

![](http://s2.quickmeme.com/img/04/04a7cc0c6176ac4bb1a6232c83122802acbb00cf5e77f9b031042e649c7d2a61.jpg)

**Comment by dashton82** [comment]
![mindblown](https://media.giphy.com/media/KI9oNS4JBemyI/giphy.gif)
