### ISSUE TITLE
Accounts API - linking to invited members that are registered

### ISSUE THREAD

**Issue by scottcowan** [SkillsFundingAgency/das-employerapprenticeshipsservice#794]
When I get the members of an account if a member has been invited but hasn't accepted they have a blank UserRef even though they are already a registered user.

## Get Members
```json
[{
    "UserRef": "",
    "Name": "Floyd Price",
    "Email": "floyd.price@test.local",
    "Role": "Viewer"
}]
```

I would like to see the UserRef so that I can create links to that user on the support console.

![](https://cdn.meme.am/cache/instances/folder858/60093858.jpg)

**Comment by dashton82** [comment]
This is probably related to test data  - the users in each environment are cleared on deployment as part of the CI tests. This can mean that the user can exist in Idams but not EAS
