### ISSUE TITLE
Account API - Invitation status for a user

### ISSUE THREAD

**Issue by scottcowan** [SkillsFundingAgency/das-employerapprenticeshipsservice#795]
I want to see the invitation status of users on an account.

Some states we're interested in are
- Invitation awaiting response
- Active
- Invitation expired

and anything else you might have

It's for use on this page on the support console

![image](https://cloud.githubusercontent.com/assets/39366/26313145/d07ae49c-3f01-11e7-8438-5cb03b64ec84.png)

![](https://img.memesuper.com/b76271ce90adcda107e3389a77d491b4_17-best-images-about-corgi-birthday-on-pinterest-dog-cards-birthday-invitation-meme_499-415.jpeg)

**Comment by dashton82** [comment]
These already come through as part of the response

**Comment by mikefee** [comment]
Bug created on AML backlog: https://skillsfundingagency.atlassian.net/browse/AML-1342
