### ISSUE TITLE
Account API - Current funds for an account

### ISSUE THREAD

**Issue by JoseviAgullo** [SkillsFundingAgency/das-employerapprenticeshipsservice#858]
I want to see the current funds for an account.

Something similar to what you have in here.

<img width="419" alt="screen shot 2017-06-20 at 16 12 44" src="https://user-images.githubusercontent.com/5517584/27341010-f18bc37a-55d3-11e7-925b-1d76cc1464fb.png">

**Comment by mikefee** [comment]
Currently being addressed by this story: 
Expose current funds in Account API https://skillsfundingagency.atlassian.net/browse/AML-1337
