### ISSUE TITLE
Getting levy declarations for all periods

### ISSUE THREAD

**Issue by scottcowan** [SkillsFundingAgency/das-employerapprenticeshipsservice#861]
I would like to see all levy declarations for an account

Currently I have to specify the period in which I want levy declarations returned

```c#
var client = new SFA.DAS.EAS.Account.Api.Client.AccountApiClient(config);
client.GetResource<SFA.DAS.EAS.Account.Api.Types.AccountResourceList<SFA.DAS.EAS.Account.Api.Types.LevyDeclarationViewModel>>("/api/accounts/84VBNV/levy/17-18/1");
```

Currently you have to go through all of the periods in order to see which declarations have occurred

![image](https://user-images.githubusercontent.com/39366/27377064-cdc6d752-566b-11e7-941f-d8ce9f25890d.png)

**Comment by mikefee** [comment]
Story on AML backlog created for this: https://skillsfundingagency.atlassian.net/browse/AML-1344
