### ISSUE TITLE
Api Client : Missing Model

### ISSUE THREAD

**Issue by scottcowan** [SkillsFundingAgency/das-employerapprenticeshipsservice#975]
It looks like the Types package wasn't published after the client was

> Reference to type 'TransactionSummaryViewModel' claims it is defined in 'SFA.DAS.EAS.Account.Api.Types', but it could not be found

I get this when trying to 

```c#
client.GetTransactionSummary("84BBBB");
```
![](https://media.giphy.com/media/wf71hhNOVYGK4/giphy.gif)

**Comment by dashton82** [comment]
The account API types needs to be updated separately to get around this issue
